using System;
using System.Collections.Generic;
using System.Text;

namespace hotel_management
{
    class Guest
    {
        // usually id being generated by the DB , but since i didnt use DB here i am assuming i can use Guid autogenerator.
        private Guid id;
        private string fullName;
        private string phoneNumber;
        private string Email;

        public Guest(string fullName, string phoneNumber, string email)
        {
            this.id = Guid.NewGuid();
            this.fullName = fullName;
            this.phoneNumber = phoneNumber;
            Email = email;
        }
        public void Display()
        {
            Console.WriteLine("Guest id is " + this.fullName + " "+ this.id);   
        }
    }
}
