using System;
using System.Collections.Generic;
using System.Text;

namespace hotel_management
{
    class Hotel
    {
        private Guid hotelID;
        public string name;
        public string address;
        public List<Room> roomsList;

        public Guid HotelID { get => hotelID; set => hotelID = value; }

        public Hotel(string name,string address)
        {
            this.HotelID = Guid.NewGuid();
            this.name = name;
            this.address = address;
            this.roomsList = new List<Room>();
        }
        public static void BookARoom()
        {
            
        }
        // usually roomid ( room number ) being generated by the DB or some other logic , in this example i used GUID.
        public void AddRoom(Hotel hotel,RoomType roomTyp)
        {
            hotel.roomsList.Add(new Room(hotel, roomTyp));
        }


    }

   
}
